site_name: Extrapolations Docs
site_url: https://docs.extrapolations.dev
copyright: Copyright 2019 - 2021 Daniel Rodriguez

nav:
  - Home: index.md
  - JupyterHub AMI:
    - Overview: jupyterhub-ami/index.md
    - Getting started: jupyterhub-ami/getting-started.md
    - IDEs: jupyterhub-ami/ides.md
    - User management: jupyterhub-ami/users.md
    - Packages: jupyterhub-ami/packages.md
    - Managemeent: jupyterhub-ami/management.md
    - SSL: jupyterhub-ami/ssl.md
    - Stoping: jupyterhub-ami/stop.md

theme:
  name: material
  custom_dir: docs/theme
  favicon: assets/img/favicon.png
  logo: assets/img/logo.png

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

plugins:
  - search
  - mkdocs-jupyter:
      execute: true

markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

google_analytics:
  - "UA-35523657-5"
  - "auto"
