site_name: Extrapolations Docs
site_url: https://docs.extrapolations.dev
copyright: Copyright 2019 - 2021 Daniel Rodriguez

nav:
  - Home: index.md
  - JupyterHub AMI:
    - Overview: jupyterhub-ami/index.md
    - Launch in EC2: jupyterhub-ami/launch.md
    - IDEs: jupyterhub-ami/ides.md
    - User management: jupyterhub-ami/users.md
    - Packages: jupyterhub-ami/packages.md
    - Management: jupyterhub-ami/management.md
    - SSL: jupyterhub-ami/ssl.md
    - Terminating: jupyterhub-ami/terminate.md
  - GPT-2:
    - Overview: models/gpt-2/index.md
    - Launch in SageMaker: models/gpt-2/launch.md
    - API: models/gpt-2/api.md
    - Examples: models/gpt-2/examples.md
    - Performance: models/gpt-2/performance.md
    - Terminating: models/gpt-2/terminate.md
  - EfficientNet-B3:
    - Overview: models/efficientnet-b3/index.md
    - Launch in SageMaker: models/efficientnet-b3/launch.md
    - API: models/efficientnet-b3/api.md
    - Examples: models/efficientnet-b3/examples.md
    - Terminating: models/efficientnet-b3/terminate.md

theme:
  name: material
  custom_dir: docs/theme
  favicon: assets/img/favicon.png
  logo: assets/img/logo.png

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

plugins:
  - search

markdown_extensions:
  - meta
  - admonition
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true

google_analytics:
  - "UA-35523657-5"
  - "auto"
